- name: Deploy ProTask App
  hosts: protask
  become: yes

  tasks:
    - name: Ensure git installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Ensure docker running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull latest code
      shell: |
        cd /home/ubuntu/html-js-node-mongo-app
        git pull origin main

    - name: Rebuild and restart app
      shell: |
        cd /home/ubuntu/html-js-node-mongo-app/deploy
        docker compose down
        docker compose build --no-cache
        docker compose up -d
